---
title: \Large \bf Papers for Presentations
author: 
institute: 
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: false
urlcolor: blue
fontsize: 12pt
header-includes: |
  \usepackage[longnamesfirst]{natbib}
  \usepackage{amsmath}
  \usepackage{amsfonts}
  \usepackage{rotating}
  \usepackage{setspace}\doublespacing
  \usepackage{floatrow}
   \floatsetup[figure]{capposition=top}

---
# Instructions

In your groups of 1-3, select one of the papers from the list below to present on. E-mail me (arw@berkeley.edu) with your paper selection and who is in your group. Papers are first-come-first-serve; it may be smart to send me a 2nd and 3rd choice in case your first has been taken. 

\newpage
# Papers

Anna Aizer and Joseph J. Doyle, Jr, "Juvenile Incarceration, Human Capital, and Future Crime: Evidence from Randomly Assigned Judges," *Quarterly Journal of Economics* 130, no. 2 (2015), 759-803.

Douglas Almond, "Is the 1918 Influenza Pandemic Over? Long‐Term Effects of In Utero Influenza Exposure in the Post‐1940 U.S. Population," *Journal of Political Economy* 114, no. 4 (2006), 672-712.

Joshua D. Angist and Alan B. Krueger, "Does Compulsory School Attendance Affect Schooling and Earnings?," *Quarterly Journal of Economics* 106, no. 4 (1991), 979-1014.

Joshua D. Angrist and Victor Lavy, "Using Maimonides' Rule to Estimate the Effect of Class Size on Scholastic Achievement,"  *Quarterly Journal of Economics* 114, no. 2 (1999), 533–575.

Andrew B. Ayres, Kyle C. Meng, and Andrew J. Plantinga, "Do Environmental Markets Improve on Open Access? Evidence from California Groundwater Rights," *Journal of Political Economy* 129, no. 10 (2021), 2817-2860. 

Marianne Bertrand and Sendhil Mullainathan, "Are Emily and Greg More Employable than Lakisha and Jamal? A Field Experiment on Labor Market Discrimination," *American Economic Review* 94, no. 4 (2004), 991-1013.

David Card and Alan B. Krueger, "Minimum Wages and Employment: A Case Study of the Fast-Food Industry in Pennsylvania and New Jersey," *American Economic Review* 84, no. 4 (1994), 772-793.

John DiNardo and David S. Lee, "Economic Impacts of New Unionization on Private Sector Employers: 1984-2001," *Quarterly Journal of Economics* 114, no. 4 (2004), 1383–1441.

Esther Duflo and Rohini Pande, "Dams," *Quarterly Journal of Economics* 122, no. 2 (2007), 601–646.

Amy Finkelstein et al., "The Oregon Health Insurance Experiment Evidence from the First Year," *Quarterly Journal of Economics* 127, no. 3 (2012), 1057-1106.

Meredith Fowlie, Michael Greenstone, and Catherine Wolfram, "Do Energy Efficiency Investments Deliver? Evidence from the Weatherization Assistance Program," *Quarterly Journal of Economics* 133, no. 2 (2018), 1597–1644.

David A. Keiser and Joseph S. Shapiro, "Consequences of the Clean Water Act and the Demand for Water Quality," *Quarterly Journal of Economics* 134, no. 1 (2019), 349-396.




 
